version: '3.2'

services:
  dockerize:
    build: ./docker/dockerize

  db:
    build: ./docker/mysql
    restart: always
    ports:
      - "3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}"
      - "MYSQL_DATABASE=${DATABASE_NAME}"
      - "MYSQL_USER=${DATABASE_USER}"
      - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"
    links:
      - dockerize
    volumes:
      - ./:/var/www/html

  php:
    build: ./docker/php
    restart: always
    ports:
      - "9000"
    links:
      - db
      - elasticsearch
      - memcached

    volumes:
      - ./:/var/www/html
      - ~/.ssh:/home/vagrant/.ssh

    entrypoint: ./docker/php/docker-entrypoint.sh

  nginx:
    build: ./docker/nginx
    restart: always
    ports:
      - "${SERVER_PORT}:80"
      - "${SERVER_PORT_HTTPS}:443"

    env_file:
      - ./.env
    links:
      - dockerize
      - php
    extra_hosts:
      - "${SERVER_NAME}:127.0.0.1"
    volumes:
      - ./:/var/www/html
      - letsencrypt:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - ./:/var/www/html
      - letsencrypt:/etc/letsencrypt

  memcached:
    image: memcached
    restart: always
    ports:
      - "11211"

  elasticsearch:
    build: ./docker/elasticsearch
    restart: always
    ports:
      - "9200"
      - "9300"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms64m -Xmx64m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  letsencrypt: ~
